import { Deck } from "../../types/deck";
import { GITHUB_REPO_URL } from "../app/meta";

export const SAMPLE_POP_HITS_DECK: Deck = {
  schemaVersion: 1,
  id: "deck-sample-pop-classics",
  name: "All-Time Pop & Rock Classics (Sample Deck)",
  createdAt: "2025-01-01T00:00:00.000Z",
  updatedAt: "2025-01-01T00:00:00.000Z",
  source: {
    type: "sample",
    name: "Sample 80s, 90s & 2000s Hits",
    url: GITHUB_REPO_URL,
  },
  tracks: [
    {
      id: "sample-1",
      title: "Bohemian Rhapsody",
      artist: "Queen",
      album: "A Night at the Opera",
      albumArtUrl: "https://i.ytimg.com/vi/fJ9rUzIMcZQ/hqdefault.jpg",
      durationMs: 354000,
      youtubeVideoId: "fJ9rUzIMcZQ",
      youtubeTitle: "Queen - Bohemian Rhapsody (Official Video)",
      startTime: 50,
      endTime: 65,
      matchStatus: "matched",
    },
    {
      id: "sample-2",
      title: "Billie Jean",
      artist: "Michael Jackson",
      album: "Thriller",
      albumArtUrl: "https://i.ytimg.com/vi/Zi_XLOBDo_Y/hqdefault.jpg",
      durationMs: 294000,
      youtubeVideoId: "Zi_XLOBDo_Y",
      youtubeTitle: "Michael Jackson - Billie Jean (Official Video)",
      startTime: 29,
      endTime: 44,
      matchStatus: "matched",
    },
    {
      id: "sample-3",
      title: "Dancing Queen",
      artist: "ABBA",
      album: "Arrival",
      albumArtUrl: "https://i.ytimg.com/vi/VBniIiITNjs/mqdefault.jpg",
      durationMs: 230000,
      youtubeVideoId: "VBniIiITNjs",
      youtubeTitle: "ABBA-Dancing Queen [HD AUDIO]",
      startTime: 30,
      endTime: 45,
      matchStatus: "matched",
    },
    {
      id: "sample-4",
      title: "Never Gonna Give You Up",
      artist: "Rick Astley",
      album: "Whenever You Need Somebody",
      albumArtUrl: "https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
      durationMs: 213000,
      youtubeVideoId: "dQw4w9WgXcQ",
      youtubeTitle: "Rick Astley - Never Gonna Give You Up (Official Music Video)",
      startTime: 43,
      endTime: 58,
      matchStatus: "matched",
    },
    {
      id: "sample-5",
      title: "September",
      artist: "Earth, Wind & Fire",
      album: "The Best of Earth, Wind & Fire",
      albumArtUrl: "https://i.ytimg.com/vi/Gs069dndIYk/hqdefault.jpg",
      durationMs: 215000,
      youtubeVideoId: "Gs069dndIYk",
      youtubeTitle: "Earth, Wind & Fire - September (Official Video)",
      startTime: 20,
      endTime: 35,
      matchStatus: "matched",
    },
    {
      id: "sample-6",
      title: "I Wanna Dance with Somebody",
      artist: "Whitney Houston",
      album: "Whitney",
      albumArtUrl: "https://i.ytimg.com/vi/eH3giaIzONA/hqdefault.jpg",
      durationMs: 291000,
      youtubeVideoId: "eH3giaIzONA",
      youtubeTitle: "Whitney Houston - I Wanna Dance With Somebody",
      startTime: 48,
      endTime: 63,
      matchStatus: "matched",
    },
    {
      id: "sample-7",
      title: "Take On Me",
      artist: "a-ha",
      album: "Hunting High and Low",
      albumArtUrl: "https://i.ytimg.com/vi/djV11Xbc914/hqdefault.jpg",
      durationMs: 227000,
      youtubeVideoId: "djV11Xbc914",
      youtubeTitle: "a-ha - Take On Me (Official Video)",
      startTime: 32,
      endTime: 47,
      matchStatus: "matched",
    },
    {
      id: "sample-8",
      title: "Girls Just Want to Have Fun",
      artist: "Cyndi Lauper",
      album: "She's So Unusual",
      albumArtUrl: "https://i.ytimg.com/vi/PIb6AZdTr-A/hqdefault.jpg",
      durationMs: 238000,
      youtubeVideoId: "PIb6AZdTr-A",
      youtubeTitle: "Cyndi Lauper - Girls Just Want To Have Fun",
      startTime: 45,
      endTime: 60,
      matchStatus: "matched",
    },
    {
      id: "sample-9",
      title: "Africa",
      artist: "Toto",
      album: "Toto IV",
      albumArtUrl: "https://i.ytimg.com/vi/FTQbiNvZqaY/hqdefault.jpg",
      durationMs: 295000,
      youtubeVideoId: "FTQbiNvZqaY",
      youtubeTitle: "Toto - Africa (Official HD Video)",
      startTime: 62,
      endTime: 77,
      matchStatus: "matched",
    },
    {
      id: "sample-10",
      title: "Eye of the Tiger",
      artist: "Survivor",
      album: "Eye of the Tiger",
      albumArtUrl: "https://i.ytimg.com/vi/btPJPFnesV4/hqdefault.jpg",
      durationMs: 245000,
      youtubeVideoId: "btPJPFnesV4",
      youtubeTitle: "Survivor - Eye Of The Tiger (Official Video)",
      startTime: 32,
      endTime: 47,
      matchStatus: "matched",
    },
    {
      id: "sample-11",
      title: "Livin' on a Prayer",
      artist: "Bon Jovi",
      album: "Slippery When Wet",
      albumArtUrl: "https://i.ytimg.com/vi/YBdyc1WDlBQ/mqdefault.jpg",
      durationMs: 249000,
      youtubeVideoId: "YBdyc1WDlBQ",
      youtubeTitle: "Livin' On A Prayer",
      startTime: 82,
      endTime: 97,
      matchStatus: "matched",
    },
    {
      id: "sample-12",
      title: "Don't Stop Believin'",
      artist: "Journey",
      album: "Escape",
      albumArtUrl: "https://i.ytimg.com/vi/1k8craCGpgs/hqdefault.jpg",
      durationMs: 251000,
      youtubeVideoId: "1k8craCGpgs",
      youtubeTitle: "Journey - Don't Stop Believin' (Audio)",
      startTime: 48,
      endTime: 63,
      matchStatus: "matched",
    },
    {
      id: "sample-13",
      title: "Rocket Man",
      artist: "Elton John",
      album: "Honky Château",
      albumArtUrl: "https://i.ytimg.com/vi/DtVBCG6ThDk/hqdefault.jpg",
      durationMs: 281000,
      youtubeVideoId: "DtVBCG6ThDk",
      youtubeTitle: "Elton John - Rocket Man (Official Music Video)",
      startTime: 60,
      endTime: 75,
      matchStatus: "matched",
    },
    {
      id: "sample-14",
      title: "Hey Jude",
      artist: "The Beatles",
      album: "Hey Jude",
      albumArtUrl: "https://i.ytimg.com/vi/A_MjCqQoLLA/hqdefault.jpg",
      durationMs: 431000,
      youtubeVideoId: "A_MjCqQoLLA",
      youtubeTitle: "The Beatles - Hey Jude",
      startTime: 30,
      endTime: 45,
      matchStatus: "matched",
    },
    {
      id: "sample-15",
      title: "Superstition",
      artist: "Stevie Wonder",
      album: "Talking Book",
      albumArtUrl: "https://i.ytimg.com/vi/0CFuCYNx-1g/hqdefault.jpg",
      durationMs: 245000,
      youtubeVideoId: "0CFuCYNx-1g",
      youtubeTitle: "Stevie Wonder - Superstition",
      startTime: 20,
      endTime: 35,
      matchStatus: "matched",
    },
    {
      id: "sample-16",
      title: "Like a Prayer",
      artist: "Madonna",
      album: "Like a Prayer",
      albumArtUrl: "https://i.ytimg.com/vi/79fzeNUqQbQ/hqdefault.jpg",
      durationMs: 341000,
      youtubeVideoId: "79fzeNUqQbQ",
      youtubeTitle: "Madonna - Like A Prayer (Official Video)",
      startTime: 65,
      endTime: 80,
      matchStatus: "matched",
    },
    {
      id: "sample-17",
      title: "Purple Rain",
      artist: "Prince",
      album: "Purple Rain",
      albumArtUrl: "https://i.ytimg.com/vi/TvnYmWpD_T8/hqdefault.jpg",
      durationMs: 520000,
      youtubeVideoId: "TvnYmWpD_T8",
      youtubeTitle: "Prince - Purple Rain (Official Video)",
      startTime: 110,
      endTime: 125,
      matchStatus: "matched",
    },
    {
      id: "sample-18",
      title: "Careless Whisper",
      artist: "George Michael",
      album: "Make It Big",
      albumArtUrl: "https://i.ytimg.com/vi/izGwDsrQ1eQ/hqdefault.jpg",
      durationMs: 302000,
      youtubeVideoId: "izGwDsrQ1eQ",
      youtubeTitle: "George Michael - Careless Whisper (Official Video)",
      startTime: 18,
      endTime: 33,
      matchStatus: "matched",
    },
    {
      id: "sample-19",
      title: "I Want It That Way",
      artist: "Backstreet Boys",
      album: "Millennium",
      albumArtUrl: "https://i.ytimg.com/vi/4fndeDfaWCg/hqdefault.jpg",
      durationMs: 213000,
      youtubeVideoId: "4fndeDfaWCg",
      youtubeTitle: "Backstreet Boys - I Want It That Way",
      startTime: 46,
      endTime: 61,
      matchStatus: "matched",
    },
    {
      id: "sample-20",
      title: "...Baby One More Time",
      artist: "Britney Spears",
      album: "...Baby One More Time",
      albumArtUrl: "https://i.ytimg.com/vi/C-u5WLJ9Yk4/mqdefault.jpg",
      durationMs: 211000,
      youtubeVideoId: "C-u5WLJ9Yk4",
      youtubeTitle: "Britney Spears - ...Baby One More Time (Official Video)",
      startTime: 43,
      endTime: 58,
      matchStatus: "matched",
    },
    {
      id: "sample-21",
      title: "Wannabe",
      artist: "Spice Girls",
      album: "Spice",
      albumArtUrl: "https://i.ytimg.com/vi/gJLIiF15wjQ/hqdefault.jpg",
      durationMs: 173000,
      youtubeVideoId: "gJLIiF15wjQ",
      youtubeTitle: "Spice Girls - Wannabe",
      startTime: 45,
      endTime: 60,
      matchStatus: "matched",
    },
    {
      id: "sample-22",
      title: "Lose Yourself",
      artist: "Eminem",
      album: "8 Mile",
      albumArtUrl: "https://i.ytimg.com/vi/_Yhyp-_hX2s/hqdefault.jpg",
      durationMs: 326000,
      youtubeVideoId: "_Yhyp-_hX2s",
      youtubeTitle: "Eminem - Lose Yourself [HD]",
      startTime: 33,
      endTime: 48,
      matchStatus: "matched",
    },
    {
      id: "sample-23",
      title: "Hey Ya!",
      artist: "Outkast",
      album: "Speakerboxxx/The Love Below",
      albumArtUrl: "https://i.ytimg.com/vi/PWgvGjAhvIw/hqdefault.jpg",
      durationMs: 235000,
      youtubeVideoId: "PWgvGjAhvIw",
      youtubeTitle: "Outkast - Hey Ya! (Official HD Video)",
      startTime: 50,
      endTime: 65,
      matchStatus: "matched",
    },
    {
      id: "sample-24",
      title: "Mr. Brightside",
      artist: "The Killers",
      album: "Hot Fuss",
      albumArtUrl: "https://i.ytimg.com/vi/gGdGFtwCNBE/hqdefault.jpg",
      durationMs: 222000,
      youtubeVideoId: "gGdGFtwCNBE",
      youtubeTitle: "The Killers - Mr. Brightside (Official Music Video)",
      startTime: 48,
      endTime: 63,
      matchStatus: "matched",
    },
    {
      id: "sample-25",
      title: "Viva La Vida",
      artist: "Coldplay",
      album: "Viva La Vida",
      albumArtUrl: "https://i.ytimg.com/vi/dvgZkm1xWPE/hqdefault.jpg",
      durationMs: 242000,
      youtubeVideoId: "dvgZkm1xWPE",
      youtubeTitle: "Coldplay - Viva La Vida (Official Video)",
      startTime: 36,
      endTime: 51,
      matchStatus: "matched",
    },
    {
      id: "sample-26",
      title: "Get Lucky",
      artist: "Daft Punk ft. Pharrell Williams",
      album: "Random Access Memories",
      albumArtUrl: "https://i.ytimg.com/vi/5NV6Rdv1a3I/hqdefault.jpg",
      durationMs: 248000,
      youtubeVideoId: "5NV6Rdv1a3I",
      youtubeTitle: "Daft Punk - Get Lucky (Official Audio)",
      startTime: 55,
      endTime: 70,
      matchStatus: "matched",
    },
    {
      id: "sample-27",
      title: "Uptown Funk",
      artist: "Mark Ronson ft. Bruno Mars",
      album: "Uptown Special",
      albumArtUrl: "https://i.ytimg.com/vi/OPf0YbXqDm0/hqdefault.jpg",
      durationMs: 270000,
      youtubeVideoId: "OPf0YbXqDm0",
      youtubeTitle: "Mark Ronson - Uptown Funk (Official Video) ft. Bruno Mars",
      startTime: 47,
      endTime: 62,
      matchStatus: "matched",
    },
    {
      id: "sample-28",
      title: "Blinding Lights",
      artist: "The Weeknd",
      album: "After Hours",
      albumArtUrl: "https://i.ytimg.com/vi/4NRXx6U8ABQ/hqdefault.jpg",
      durationMs: 200000,
      youtubeVideoId: "4NRXx6U8ABQ",
      youtubeTitle: "The Weeknd - Blinding Lights (Official Video)",
      startTime: 27,
      endTime: 42,
      matchStatus: "matched",
    },
    {
      id: "sample-29",
      title: "Levitating",
      artist: "Dua Lipa",
      album: "Future Nostalgia",
      albumArtUrl: "https://i.ytimg.com/vi/TUVcZfQe-Kw/hqdefault.jpg",
      durationMs: 203000,
      youtubeVideoId: "TUVcZfQe-Kw",
      youtubeTitle: "Dua Lipa - Levitating (Official Music Video)",
      startTime: 20,
      endTime: 35,
      matchStatus: "matched",
    },
    {
      id: "sample-30",
      title: "Shake It Off",
      artist: "Taylor Swift",
      album: "1989",
      albumArtUrl: "https://i.ytimg.com/vi/nfWlot6h_JM/hqdefault.jpg",
      durationMs: 219000,
      youtubeVideoId: "nfWlot6h_JM",
      youtubeTitle: "Taylor Swift - Shake It Off",
      startTime: 40,
      endTime: 55,
      matchStatus: "matched",
    },
  ],
};
